-- ============================================================
-- Invest Simulation (Module 4) — Seed Data
-- Excludes: asset_price_points (generated by tick engine)
-- ============================================================

BEGIN;

-- ============================================================
-- 0. SECTORS
-- ============================================================
INSERT INTO "invest"."sectors" ("id",
                                "code",
                                "name",
                                "description",
                                "sort_order",
                                "created_at")
VALUES (1, 'stock', 'Stonks 📈', 'Public companies but make it meme', 1, '2026-03-28 07:59:16.37569+00'),
       (2, 'crypto', 'Crypto Degens 🪙', 'Volatility go brrrr', 2, '2026-03-28 07:59:16.37569+00'),
       (3, 'real_estate', 'Brick & Chill 🏠', 'Slow but rich vibes', 3, '2026-03-28 07:59:16.37569+00'),
       (4, 'other', 'Shiny Stuff ✨', 'Gold, silver, diamonds & flex assets', 4, '2026-03-28 07:59:16.37569+00');
-- ============================================================
-- 0.1. ASSETS
-- ============================================================
INSERT INTO "invest"."assets" ("id",
                               "sector_id",
                               "code",
                               "name",
                               "asset_type",
                               "risk_tier",
                               "volatility_profile",
                               "attention_sensitivity",
                               "description",
                               "meta",
                               "is_active",
                               "created_at",
                               "category")
VALUES (10001, 1, 'APPLZ', 'Pear Inc. 🍐', 'stock', 'medium', 'medium', 'high', 'Consumer technology company focused on hardware, software, and ecosystem integration.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10002, 1, 'MICROHARD', 'Macrohard 💻', 'stock', 'low', 'low', 'medium', 'Global software and cloud infrastructure provider serving enterprise and consumer markets.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10003, 1, 'AMAYZON', 'AmaZone 🐍', 'stock', 'medium', 'medium', 'high', 'E-commerce and logistics platform with diversified revenue streams including cloud services.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10004, 1, 'NETFLICKS', 'Netflicks 📺', 'stock', 'medium', 'medium', 'high', 'Digital streaming platform producing and distributing subscription-based content globally.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10005, 1, 'TESLAAH', 'Teslah ⚡', 'stock', 'high', 'high', 'very_high', 'Electric vehicle and clean energy company with strong innovation in battery technology.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10006, 1, 'GOOGEL', 'Googel 🔍', 'stock', 'low', 'low', 'medium', 'Search engine and digital advertising leader with extensive data and AI capabilities.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10007, 1, 'METAH', 'Metah 🌐', 'stock', 'high', 'high', 'very_high', 'Technology company focused on social platforms and virtual/augmented reality ecosystems.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10008, 1, 'NVIDEAH', 'Nvideah 🎮', 'stock', 'medium', 'high', 'high', 'Semiconductor company specializing in GPUs and AI computing infrastructure.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10009, 1, 'SPOTIFYD', 'Spotifried 🎧', 'stock', 'medium', 'medium', 'high', 'Audio streaming platform with subscription and ad-supported revenue models.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (10010, 1, 'UBEAR', 'U-Bear 🚗', 'stock', 'high', 'high', 'very_high', 'Mobility and delivery platform operating in urban transportation networks.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'tech'),
       (11001, 2, 'BITZ', 'BitzCoin 🧠', 'crypto', 'high', 'very_high', 'very_high', 'Decentralized digital asset used as a store of value and medium of exchange.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'layer1'),
       (11002, 2, 'ETHEREAL', 'Ethereal 🔮', 'crypto', 'high', 'very_high', 'very_high', 'Blockchain platform supporting smart contracts and decentralized applications.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'layer1'),
       (11003, 2, 'DOGGO', 'Doggo Inu 🐶', 'crypto', 'extreme', 'insane', 'viral', 'Community-driven digital token with high volatility and speculative demand.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'meme'),
       (11004, 2, 'MOONER', 'Mooner 🌕', 'crypto', 'extreme', 'insane', 'viral', 'Speculative cryptocurrency driven by market sentiment and momentum trading.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'meme'),
       (11005, 2, 'RUGGY', 'Ruggy Pull 💀', 'crypto', 'extreme', 'insane', 'viral', 'High-risk token with limited transparency and elevated downside exposure.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'meme'),
       (11006, 2, 'STABLEISH', 'Stable-ish 🫠', 'crypto', 'medium', 'low', 'low', 'Digital asset designed to reduce volatility through partial stabilization mechanisms.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'stable'),
       (11007, 2, 'FOMO', 'Fomo Coin 😱', 'crypto', 'high', 'very_high', 'very_high', 'Momentum-driven cryptocurrency influenced heavily by retail investor behavior.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'meme'),
       (11008, 2, 'DEFIANT', 'Defiant 💸', 'crypto', 'high', 'very_high', 'high', 'Decentralized finance token used in lending, staking, and liquidity protocols.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'defi'),
       (11009, 2, 'APECHAIN', 'ApeChain 🦍', 'crypto', 'extreme', 'insane', 'viral', 'Blockchain ecosystem token driven by community participation and network effects.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'meme'),
       (11010, 2, 'GASGOD', 'GasGod ⛽', 'crypto', 'medium', 'high', 'medium', 'Utility token used for transaction fees within a blockchain network.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'utility'),
       (12001, 3, 'METACONDO', 'MetaCondo 🏢', 'real_estate', 'low', 'low', 'low', 'Real estate asset representing premium residential developments in urban areas.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'residential'),
       (12002, 3, 'SUBURBIA', 'Suburbia 🌳', 'real_estate', 'low', 'low', 'low', 'Portfolio of suburban residential properties with stable long-term demand.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'residential'),
       (12003, 3, 'SKYHIGH', 'SkyHigh Towers 🌆', 'real_estate', 'medium', 'medium', 'low', 'High-rise commercial and residential property assets in metropolitan locations.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'commercial'),
       (12004, 3, 'BEACHY', 'Beachy Villas 🏖️', 'real_estate', 'medium', 'medium', 'medium', 'Hospitality and vacation rental properties in coastal regions.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'hospitality'),
       (12005, 3, 'MALLCORE', 'MallCore 🛍️', 'real_estate', 'medium', 'low', 'low', 'Retail real estate assets focused on shopping centers and commercial leasing.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'commercial'),
       (12006, 3, 'WAREHOUSE', 'WareHouse 📦', 'real_estate', 'low', 'low', 'low', 'Industrial real estate supporting logistics and supply chain operations.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'industrial'),
       (12007, 3, 'OFFICELOL', 'Office LOL 🏢', 'real_estate', 'medium', 'medium', 'low', 'Office space portfolio exposed to corporate leasing demand cycles.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'commercial'),
       (12008, 3, 'COZYCRIB', 'CozyCrib 🛏️', 'real_estate', 'low', 'low', 'low', 'Entry-level residential housing targeting affordable living segments.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'residential'),
       (12009, 3, 'RENTMAX', 'RentMax 💸', 'real_estate', 'medium', 'medium', 'medium', 'Income-generating rental properties with recurring cash flow profiles.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'residential'),
       (12010, 3, 'FLIPSTER', 'Flipster 🔄', 'real_estate', 'high', 'high', 'medium', 'Short-term real estate investment focused on property renovation and resale.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'flipping'),
       (13001, 4, 'GOLDY', 'Goldy 🪙', 'commodity', 'low', 'low', 'medium', 'Precious metal asset commonly used as a hedge against inflation and economic uncertainty.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'precious_metals'),
       (13002, 4, 'SILVERBACK', 'Silverback 🦍', 'commodity', 'medium', 'medium', 'medium', 'Industrial and precious metal with applications in manufacturing and investment.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'precious_metals'),
       (13003, 4, 'DIAMOOD', 'Diamond Hands 💎', 'commodity', 'medium', 'medium', 'high', 'Luxury commodity asset with value driven by scarcity and consumer demand.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'precious_metals'),
       (13004, 4, 'PLATINAH', 'Platinah ✨', 'commodity', 'low', 'low', 'low', 'Rare metal used in industrial applications and as a store of value.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'precious_metals'),
       (13005, 4, 'OILISH', 'Oilish 🛢️', 'commodity', 'high', 'high', 'high', 'Energy commodity influenced by global supply, demand, and geopolitical factors.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'energy'),
       (13006, 4, 'URANIUMZ', 'Uraniumz ☢️', 'commodity', 'high', 'high', 'medium', 'Energy-related commodity used in nuclear power generation.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'energy'),
       (13007, 4, 'COPPERHEAD', 'Copperhead 🐍', 'commodity', 'medium', 'medium', 'low', 'Base metal essential for infrastructure, electronics, and construction.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'industrial_metals'),
       (13008, 4, 'WHEATY', 'Wheaty 🌾', 'commodity', 'low', 'low', 'low', 'Agricultural commodity tied to global food supply and demand dynamics.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'agricultural'),
       (13009, 4, 'ARTSY', 'Artsy NFT 🎨', 'commodity', 'extreme', 'insane', 'viral', 'Alternative asset class driven by collector demand and market perception.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'alternative'),
       (13010, 4, 'VINTAGE', 'Vintage Wine 🍷', 'commodity', 'medium', 'low', 'medium', 'Collectible asset with value influenced by aging, rarity, and market trends.', '{}', TRUE, '2026-03-28 07:59:23.488158+00', 'alternative');

-- ============================================================
-- 0.2. WORLD ARC TYPES
-- ============================================================
INSERT INTO "invest"."world_arc_types" ("id",
                                        "code",
                                        "name",
                                        "description")
VALUES (1, 'ai_revolution', 'AI Revolution', 'Artificial intelligence transforms industries, reshaping productivity and labor markets globally.'),
       (2, 'green_transition', 'Green Energy Transition', 'Global shift from fossil fuels to renewable energy sources, driven by policy and technology breakthroughs.'),
       (3, 'rate_hike_cycle', 'Interest Rate Hike Cycle', 'Central banks raise interest rates to combat inflation, tightening financial conditions across markets.'),
       (4, 'supply_chain_shock', 'Global Supply Chain Shock', 'Disruption to global supply chains causes shortages, price spikes, and shifts in trade patterns.'),
       (5, 'emerging_market_boom', 'Emerging Market Boom', 'Rapid growth in emerging economies attracts capital flows and reshapes global investment landscape.'),
       (6, 'crypto_regulation', 'Crypto Regulation Wave', 'Governments worldwide introduce comprehensive cryptocurrency regulations, reshaping digital asset markets.'),
       (7, 'housing_correction', 'Housing Market Correction', 'Overheated real estate markets undergo a correction, impacting banking, construction, and consumer wealth.'),
       (8, 'deglobalization', 'Deglobalization Trend', 'Nations pursue economic self-sufficiency and onshoring, reducing global trade interdependence.');

-- ============================================================
-- 1. ASSET SPOTLIGHT TEMPLATES (catalog)
-- ============================================================
INSERT INTO invest.asset_spotlight_templates (id, code, title, description, rarity, meta) VALUES
(1,  'viral_meme',        'Viral Meme Explosion',      'Asset goes viral on social media, triggering massive attention.',            1, '{"intensity": "extreme", "sentiment": "bullish"}'),
(2,  'ceo_tweet',         'CEO Tweet Storm',           'CEO''s tweet causes speculative frenzy.',                                    2, '{"intensity": "high", "sentiment": "mixed"}'),
(3,  'whale_move',        'Whale Movement Detected',   'Large holder moved significant position, sparking speculation.',             2, '{"intensity": "high", "sentiment": "mixed"}'),
(4,  'earnings_surprise', 'Earnings Surprise',         'Unexpected earnings result draws market attention.',                         3, '{"intensity": "medium", "sentiment": "bullish"}'),
(5,  'partnership_rumor', 'Partnership Rumor',          'Unconfirmed partnership rumor creates buzz.',                                3, '{"intensity": "medium", "sentiment": "bullish"}'),
(6,  'hack_scare',        'Hack Scare',               'Security vulnerability or hack report surfaces.',                             2, '{"intensity": "high", "sentiment": "bearish"}'),
(7,  'listing_hype',      'New Listing Hype',          'Asset listed on major platform, drawing fresh buyers.',                      3, '{"intensity": "medium", "sentiment": "bullish"}'),
(8,  'regulatory_probe',  'Regulatory Probe',          'Regulatory body announces investigation into asset.',                        2, '{"intensity": "high", "sentiment": "bearish"}'),
(9,  'influencer_pump',   'Influencer Pump',           'High-profile influencer endorses asset aggressively.',                       2, '{"intensity": "high", "sentiment": "bullish"}'),
(10, 'short_squeeze',     'Short Squeeze Setup',       'Short interest builds up, creating squeeze potential.',                      1, '{"intensity": "extreme", "sentiment": "bullish"}'),
(11, 'dividend_boost',    'Dividend Boost',            'Unexpected dividend increase announced.',                                    4, '{"intensity": "low", "sentiment": "bullish"}'),
(12, 'insider_sell',      'Insider Selling',           'Insider selling detected, raising concerns.',                                3, '{"intensity": "medium", "sentiment": "bearish"}');

-- ============================================================
-- 2. POLICY THREAD TEMPLATES (catalog)
-- ============================================================
INSERT INTO invest.policy_thread_templates (id, code, title, description, rarity, state_descriptions, meta) VALUES
(1, 'crypto_tax',         'Crypto Tax Framework',         'Government proposes comprehensive crypto taxation framework.',                   2,
  '{"declared_path":"Government announces plan to create crypto tax framework","action_1":"Tax bill formally introduced to parliament","action_2":"Committee passes bill in first reading","action_3":"Final vote scheduled and approved","resolution":"Crypto tax law takes effect"}',
  '{"severity": "high"}'),
(2, 'green_subsidy',      'Green Energy Subsidy Bill',    'Legislation to subsidize renewable energy investments.',                          3,
  '{"declared_path":"Government signals green energy investment incentives","action_1":"Subsidy bill drafted and submitted to congress","action_2":"Budget allocation approved for renewable programs","action_3":"Implementation timeline and eligibility published","resolution":"Green energy subsidies now active"}',
  '{"severity": "medium"}'),
(3, 'housing_cap',        'Housing Price Cap Policy',     'Government considers capping residential property prices.',                       2,
  '{"declared_path":"Officials publicly discuss housing price intervention","action_1":"Price cap proposal submitted for review","action_2":"Regional pilot program launched in 3 cities","action_3":"Nationwide rollout plan approved","resolution":"Housing price caps enforced nationwide"}',
  '{"severity": "high"}'),
(4, 'ai_regulation',      'AI Industry Regulation',       'New regulatory framework for AI development and deployment.',                     2,
  '{"declared_path":"Government forms AI regulation task force","action_1":"Draft regulation framework published for comment","action_2":"Compliance requirements finalized for AI companies","action_3":"Enforcement agency established with oversight powers","resolution":"AI regulatory framework fully operational"}',
  '{"severity": "high"}'),
(5, 'trade_tariff',       'Import Tariff Hike',           'Proposed tariff increase on imported goods affecting supply chains.',              3,
  '{"declared_path":"Trade ministry signals tariff review on imports","action_1":"Proposed tariff schedule released for public comment","action_2":"Tariff rates finalized after industry consultation","action_3":"Implementation date set, grace period announced","resolution":"New import tariffs in effect"}',
  '{"severity": "medium"}'),
(6, 'rate_freeze',        'Interest Rate Freeze',         'Central bank signals rate freeze for extended period.',                            3,
  '{"declared_path":"Central bank hints at pausing rate adjustments","action_1":"Official statement confirms rate hold for next quarter","action_2":"Rate freeze extended through end of year","action_3":"Forward guidance signals continued freeze into next year","resolution":"Extended rate freeze period concluded"}',
  '{"severity": "medium"}'),
(7, 'mining_ban',         'Crypto Mining Ban',            'Environmental concerns trigger proposal to ban crypto mining.',                    1,
  '{"declared_path":"Environmental agency flags crypto mining energy consumption","action_1":"Mining ban bill introduced citing carbon targets","action_2":"Emergency restrictions placed on new mining operations","action_3":"Full ban approved with 6-month transition period","resolution":"Crypto mining officially banned"}',
  '{"severity": "extreme"}'),
(8, 'antitrust_probe',    'Tech Antitrust Investigation', 'Antitrust investigation launched against major tech companies.',                  2,
  '{"declared_path":"Regulators announce antitrust inquiry into big tech","action_1":"Formal investigation opened, document subpoenas issued","action_2":"Preliminary findings suggest market dominance abuse","action_3":"Remedies proposed including potential breakup orders","resolution":"Antitrust ruling delivered"}',
  '{"severity": "high"}'),
(9, 'commodity_reserve',  'Strategic Commodity Reserve',   'Government building strategic reserves of key commodities.',                     3,
  '{"declared_path":"Government announces strategic reserve expansion plan","action_1":"Budget approved for large-scale commodity purchases","action_2":"Bulk buying contracts signed for metals and energy","action_3":"Reserve storage facilities expanded and stocked","resolution":"Strategic reserve targets achieved"}',
  '{"severity": "medium"}'),
(10, 'rental_regulation', 'Rental Market Regulation',     'New regulations on rental yields and tenant protections.',                        3,
  '{"declared_path":"Housing ministry proposes rental market reforms","action_1":"Rent control framework drafted with yield caps","action_2":"Tenant protection standards legislated","action_3":"Landlord compliance deadlines set","resolution":"Rental regulations fully enforced"}',
  '{"severity": "medium"}');

-- ============================================================
-- 2.1. POLICY SECTOR IMPACTS
-- (templateId references policy_thread_templates)
-- Weight range: -1.0 to +1.0
-- Negative = bearish impact, Positive = bullish impact
-- Category-specific entries override sector-wide
-- ============================================================
INSERT INTO invest.policy_sector_impacts (template_id, sector_id, category, weight) VALUES
-- Policy 1: Crypto Tax Framework
(1, 1, NULL,       0.05),   -- stocks (slight flight to safety)
(1, 2, NULL,      -0.50),   -- crypto (sector-wide bearish)
(1, 2, 'meme',   -0.80),   -- crypto/meme — hammered
(1, 2, 'defi',   -0.60),   -- crypto/defi — compliance costs
(1, 2, 'stable', -0.15),   -- crypto/stable — less affected
(1, 3, NULL,       0.05),   -- real_estate (mild safe haven)
(1, 4, NULL,       0.03),   -- other (negligible)
(1, 4, 'precious_metals', 0.10), -- gold/silver mild safe haven

-- Policy 2: Green Energy Subsidy Bill
(2, 1, NULL,       0.10),   -- stocks (mixed positive)
(2, 1, 'tech',     0.20),   -- stocks/tech — clean tech benefit
(2, 2, NULL,      -0.05),   -- crypto (mining concern)
(2, 3, NULL,       0.15),   -- real_estate (green building premium)
(2, 3, 'commercial', 0.25), -- commercial retrofits
(2, 4, NULL,       0.20),   -- other (commodities benefit)
(2, 4, 'energy',   0.60),   -- direct energy beneficiary
(2, 4, 'industrial_metals', 0.40), -- copper/lithium demand

-- Policy 3: Housing Price Cap
(3, 1, NULL,       0.00),   -- stocks (neutral)
(3, 2, NULL,       0.05),   -- crypto (slight alt-investment narrative)
(3, 3, NULL,      -0.45),   -- real_estate (direct hit)
(3, 3, 'residential', -0.70), -- residential worst hit
(3, 3, 'flipping', -0.80),  -- flipping destroyed
(3, 3, 'commercial', -0.20), -- commercial less affected
(3, 3, 'industrial', -0.10), -- industrial resilient
(3, 4, NULL,       0.05),   -- other (negligible)

-- Policy 4: AI Industry Regulation
(4, 1, NULL,      -0.15),   -- stocks (mixed)
(4, 1, 'tech',    -0.45),   -- stocks/tech — direct target
(4, 2, NULL,       0.00),   -- crypto (neutral)
(4, 2, 'utility', -0.10),   -- crypto/utility — AI-token impact
(4, 3, NULL,       0.00),   -- real_estate (neutral)
(4, 4, NULL,       0.05),   -- other (mild safe haven)

-- Policy 5: Import Tariff Hike
(5, 1, NULL,      -0.20),   -- stocks (trade disruption)
(5, 1, 'tech',    -0.30),   -- tech supply chain sensitive
(5, 2, NULL,       0.05),   -- crypto (borderless narrative)
(5, 3, NULL,       0.00),   -- real_estate (neutral)
(5, 4, NULL,       0.25),   -- other (domestic commodities benefit)
(5, 4, 'agricultural', 0.35), -- food price pressure
(5, 4, 'industrial_metals', 0.30), -- metals tariff benefit

-- Policy 6: Interest Rate Freeze
(6, 1, NULL,       0.15),   -- stocks (positive certainty)
(6, 1, 'tech',     0.25),   -- tech likes low/frozen rates
(6, 2, NULL,       0.10),   -- crypto (risk-on signal)
(6, 3, NULL,       0.20),   -- real_estate (mortgage stability)
(6, 3, 'residential', 0.30), -- residential most benefits
(6, 4, NULL,       0.05),   -- other (mild)

-- Policy 7: Crypto Mining Ban
(7, 1, NULL,       0.03),   -- stocks (negligible)
(7, 2, NULL,      -0.60),   -- crypto (severe)
(7, 2, 'meme',   -0.85),   -- crypto/meme — devastated
(7, 2, 'layer1', -0.70),    -- crypto/layer1 — fundamental threat
(7, 2, 'defi',   -0.50),    -- crypto/defi — collateral damage
(7, 2, 'stable', -0.20),    -- crypto/stable — partially shielded
(7, 3, NULL,       0.00),   -- real_estate (neutral)
(7, 4, NULL,       0.08),   -- other (mild safe haven)
(7, 4, 'precious_metals', 0.15), -- gold as alternative

-- Policy 8: Tech Antitrust Investigation
(8, 1, NULL,      -0.10),   -- stocks (mixed)
(8, 1, 'tech',    -0.50),   -- stocks/tech — direct target
(8, 2, NULL,       0.05),   -- crypto (decentralization narrative)
(8, 3, NULL,       0.00),   -- real_estate (neutral)
(8, 4, NULL,       0.03),   -- other (negligible)

-- Policy 9: Strategic Commodity Reserve
(9, 1, NULL,       0.05),   -- stocks (mild positive infrastructure)
(9, 2, NULL,       0.00),   -- crypto (neutral)
(9, 3, NULL,       0.05),   -- real_estate (construction materials)
(9, 4, NULL,       0.35),   -- other (commodities direct beneficiary)
(9, 4, 'precious_metals', 0.50), -- gold/silver stockpiling
(9, 4, 'energy',   0.40),   -- energy reserves
(9, 4, 'industrial_metals', 0.45), -- strategic metals
(9, 4, 'agricultural', 0.30), -- food reserves

-- Policy 10: Rental Market Regulation
(10, 1, NULL,      0.00),   -- stocks (neutral)
(10, 2, NULL,      0.00),   -- crypto (neutral)
(10, 3, NULL,     -0.30),   -- real_estate (mixed)
(10, 3, 'residential', -0.50), -- residential rental yields hit
(10, 3, 'commercial', -0.10), -- commercial spillover
(10, 3, 'hospitality', -0.40), -- hospitality regulation fear
(10, 4, NULL,      0.03);   -- other (negligible)

-- ============================================================
-- 3. WORLD ARC SECTOR IMPACTS
-- (arcTypeId references existing world_arc_types)
-- Weight range: -1.0 to +1.0
-- Category-specific entries override sector-wide
-- ============================================================
INSERT INTO invest.world_arc_sector_impacts (arc_type_id, sector_id, category, weight) VALUES
-- Arc 1: AI Revolution
(1, 1, NULL,       0.60),   -- stocks (sector-wide)
(1, 1, 'tech',     0.85),   -- stocks/tech — primary beneficiary
(1, 2, NULL,       0.20),   -- crypto (some AI-crypto overlap)
(1, 2, 'utility',  0.35),   -- crypto/utility — compute tokens
(1, 3, NULL,      -0.05),   -- real_estate (neutral-slight negative, capital shifts to tech)
(1, 4, NULL,       0.10),   -- other (minor positive)
(1, 4, 'energy',   0.25),   -- other/energy — data center demand

-- Arc 2: Green Energy Transition
(2, 1, NULL,       0.15),   -- stocks (mixed)
(2, 1, 'tech',     0.30),   -- stocks/tech — clean tech beneficiaries
(2, 2, NULL,      -0.10),   -- crypto (energy-intensive mining concern)
(2, 2, 'defi',     0.05),   -- crypto/defi — green DeFi narratives
(2, 3, NULL,       0.20),   -- real_estate (green buildings premium)
(2, 3, 'commercial', 0.35), -- real_estate/commercial — retrofit demand
(2, 4, NULL,       0.40),   -- other (commodities benefit)
(2, 4, 'energy',   0.80),   -- other/energy — direct beneficiary
(2, 4, 'industrial_metals', 0.60), -- other/industrial metals — copper/lithium demand
(2, 4, 'precious_metals',  0.10),  -- other/precious — mild hedge

-- Arc 3: Interest Rate Hike Cycle
(3, 1, NULL,      -0.30),   -- stocks (rate sensitive)
(3, 1, 'tech',    -0.50),   -- stocks/tech — growth stocks hammered
(3, 2, NULL,      -0.40),   -- crypto (risk-off)
(3, 2, 'stable',   0.10),   -- crypto/stable — flight to stability
(3, 2, 'meme',    -0.70),   -- crypto/meme — speculative crush
(3, 3, NULL,      -0.35),   -- real_estate (mortgage rates up)
(3, 3, 'residential', -0.50), -- real_estate/residential — hardest hit
(3, 3, 'industrial',  -0.10), -- real_estate/industrial — more resilient
(3, 4, NULL,       0.15),   -- other (commodities as hedge)
(3, 4, 'precious_metals', 0.30), -- gold/silver benefit

-- Arc 4: Global Supply Chain Shock
(4, 1, NULL,      -0.20),   -- stocks
(4, 1, 'tech',    -0.35),   -- stocks/tech — chip shortage
(4, 2, NULL,       0.05),   -- crypto (decentralization narrative)
(4, 3, NULL,      -0.15),   -- real_estate (construction delays)
(4, 3, 'industrial', -0.40), -- real_estate/industrial — logistics chaos
(4, 4, NULL,       0.30),   -- other (commodities spike)
(4, 4, 'energy',   0.50),   -- energy price spike
(4, 4, 'agricultural', 0.45), -- food supply pressure
(4, 4, 'industrial_metals', 0.40), -- metals shortage

-- Arc 5: Emerging Market Boom
(5, 1, NULL,       0.25),   -- stocks (EM exposure)
(5, 1, 'tech',     0.15),   -- stocks/tech — some EM expansion
(5, 2, NULL,       0.35),   -- crypto (EM adoption)
(5, 2, 'layer1',   0.50),   -- crypto/layer1 — infrastructure demand
(5, 3, NULL,       0.20),   -- real_estate (EM property boom)
(5, 3, 'residential', 0.30), -- residential demand
(5, 4, NULL,       0.30),   -- other (commodity demand)
(5, 4, 'industrial_metals', 0.55), -- infrastructure buildout

-- Arc 6: Crypto Regulation Wave
(6, 1, NULL,       0.05),   -- stocks (minimal direct impact)
(6, 2, NULL,      -0.45),   -- crypto (regulation pressure)
(6, 2, 'meme',    -0.80),   -- crypto/meme — devastated
(6, 2, 'defi',    -0.60),   -- crypto/defi — compliance costs
(6, 2, 'stable',   0.20),   -- crypto/stable — legitimized
(6, 2, 'layer1',  -0.30),   -- crypto/layer1 — mixed
(6, 2, 'utility',  -0.20),  -- crypto/utility — moderate pressure
(6, 3, NULL,       0.00),   -- real_estate (unaffected)
(6, 4, NULL,       0.05),   -- other (slight safe haven)

-- Arc 7: Housing Market Correction
(7, 1, NULL,      -0.10),   -- stocks (wealth effect)
(7, 1, 'tech',     0.00),   -- stocks/tech — relatively insulated
(7, 2, NULL,       0.10),   -- crypto (alternative asset narrative)
(7, 3, NULL,      -0.55),   -- real_estate (direct hit)
(7, 3, 'residential', -0.75), -- residential worst hit
(7, 3, 'commercial',  -0.45), -- commercial follows
(7, 3, 'hospitality', -0.35), -- hospitality affected
(7, 3, 'flipping',    -0.90), -- flipping destroyed
(7, 3, 'industrial',  -0.20), -- industrial more resilient
(7, 4, NULL,       0.15),   -- other (flight to safety)
(7, 4, 'precious_metals', 0.35), -- gold as safe haven

-- Arc 8: Deglobalization Trend
(8, 1, NULL,      -0.15),   -- stocks (trade disruption)
(8, 1, 'tech',    -0.25),   -- stocks/tech — global supply chains
(8, 2, NULL,       0.15),   -- crypto (borderless narrative)
(8, 2, 'layer1',   0.25),   -- crypto/layer1 — decentralization appeal
(8, 3, NULL,       0.10),   -- real_estate (onshoring = domestic demand)
(8, 3, 'industrial', 0.30), -- industrial/warehouse — reshoring
(8, 4, NULL,       0.20),   -- other (domestic commodities)
(8, 4, 'agricultural', 0.35), -- food security premium
(8, 4, 'energy',   0.30);   -- energy independence push

-- ============================================================
-- 4. WORLD ARC INSTANCES (active FSMs)
-- Must start in 'spark' (background never self-transitions).
-- 3 arcs active from the start for layered market dynamics.
-- started_at_tick=1, ticks_in_current_state=0, progress=0.10 (spark base)
-- ============================================================
INSERT INTO invest.world_arc_instances
  (id, arc_type_id, state, ticks_in_current_state, progress, started_at_tick, ended_at_tick, is_active, meta) VALUES
(1, 1, 'spark', 0, 0.10, 1, NULL, true, '{}'),   -- AI Revolution: bullish tech/stocks, mild crypto boost
-- (2, 3, 'spark', 0, 0.10, 1, NULL, true, '{}'),   -- Interest Rate Hike Cycle: bearish growth stocks & crypto, bullish precious metals
(3, 6, 'spark', 0, 0.10, 1, NULL, true, '{}');   -- Crypto Regulation Wave: bearish meme/defi, bullish stablecoins

-- ============================================================
-- 5. ASSET SPOTLIGHT INSTANCES (active FSMs)
-- Must start in 'emerging' (dormant never self-transitions).
-- Each targets a specific asset. Mix across sectors for variety.
-- started_at_tick=1, ticks_in_current_state=0
-- ============================================================
INSERT INTO invest.asset_spotlight_instances
  (id, template_id, asset_id, state, ticks_in_current_state, started_at_tick, ended_at_tick, cooldown_until_tick, is_active, meta) VALUES
-- Stock spotlights
(1,  9,  10005, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Influencer Pump on Teslah ⚡ (high vol, very_high attention)
(2,  4,  10008, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Earnings Surprise on Nvideah 🎮 (AI chip demand narrative)
(3,  2,  10007, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- CEO Tweet Storm on Metah 🌐 (high vol, very_high attention)
-- Crypto spotlights
(4,  1,  11003, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Viral Meme Explosion on Doggo Inu 🐶 (extreme/insane/viral)
(5,  3,  11001, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Whale Movement on BitzCoin 🧠 (high vol, very_high attention)
(6,  6,  11008, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Hack Scare on Defiant 💸 (bearish — DeFi security concern)
-- Real estate spotlight
(7,  10, 12010, 'emerging', 0, 1, NULL, NULL, true, '{}'),   -- Short Squeeze on Flipster 🔄 (high vol flipping asset)
-- Commodity spotlight
(8,  5,  13009, 'emerging', 0, 1, NULL, NULL, true, '{}');   -- Partnership Rumor on Artsy NFT 🎨 (extreme/insane/viral)

-- ============================================================
-- 6. POLICY THREAD INSTANCES (active FSMs)
-- Must start in 'declared_path' (undeclared never self-transitions).
-- actions_total=3, actions_completed=0
-- started_at_tick=1
-- ============================================================
INSERT INTO invest.policy_thread_instances
  (id, template_id, state, ticks_in_current_state, actions_total, actions_completed, started_at_tick, resolved_at_tick, is_active, meta) VALUES
(1, 4,  'declared_path', 0, 3, 0, 1, NULL, true, '{}'),   -- AI Industry Regulation (affects stocks/tech — aligns with AI Revolution arc)
(2, 1,  'declared_path', 0, 3, 0, 1, NULL, true, '{}'),   -- Crypto Tax Framework (affects crypto — aligns with Crypto Regulation arc)
-- (3, 6,  'declared_path', 0, 3, 0, 1, NULL, true, '{}');   -- Interest Rate Freeze (affects stocks + real_estate — aligns with Rate Hike arc)

-- ============================================================
-- 7. REFLECTION TEMPLATES
-- ============================================================
INSERT INTO invest.reflection_templates (id, code, title, body_template, condition, meta) VALUES
-- High turnover reflections
(1, 'high_turnover_warning',
   'Trading Frenzy Alert',
   'Your turnover score hit {{turnover}} this window. High-frequency trading often erodes returns through transaction costs. Consider whether each trade has a clear thesis.',
   '{"minTurnover": 3.0}',
   '{"category": "trading_behavior"}'),

(2, 'moderate_turnover',
   'Active Trader',
   'With a turnover of {{turnover}}, you''re trading actively. This can be profitable if deliberate, but watch for emotional decisions.',
   '{"minTurnover": 1.5, "maxTurnover": 3.0}',
   '{"category": "trading_behavior"}'),

-- Volatility chasing
(3, 'volatility_chaser',
   'Chasing the Hype',
   'Your volatility chasing score is {{volatilityChasing}}. You''re drawn to the action — but the crowd is usually already priced in by the time you arrive.',
   '{"minVolatilityChasing": 0.6}',
   '{"category": "risk_behavior"}'),

(4, 'calm_trader',
   'Cool Under Pressure',
   'Volatility chasing score: {{volatilityChasing}}. You''re not easily swayed by market noise. This patience is a genuine edge.',
   '{"maxVolatilityChasing": 0.2}',
   '{"category": "risk_behavior"}'),

-- Concentration
(5, 'concentration_spike',
   'Eggs in One Basket',
   'Concentration shifted by {{concentrationChange}} — your portfolio is becoming less diversified. One bad event could hit harder than expected.',
   '{"minConcentrationChange": 0.15}',
   '{"category": "diversification"}'),

(6, 'diversifying_well',
   'Spreading the Risk',
   'Your concentration decreased by {{concentrationChange}}. You''re building a more balanced portfolio — this helps smooth out surprises.',
   '{"maxConcentrationChange": -0.10}',
   '{"category": "diversification"}'),

-- Reaction time
(7, 'fast_reactor',
   'Hair Trigger',
   'Average reaction time: {{reactionTime}} ticks. You''re reacting very quickly to news. Speed can help, but snap decisions often miss the full picture.',
   '{"maxReactionTime": 1.5}',
   '{"category": "timing"}'),

(8, 'slow_and_steady',
   'Measured Response',
   'Reaction time of {{reactionTime}} ticks shows you''re taking time to process news before acting. This deliberate approach often leads to better outcomes.',
   '{"minReactionTime": 4.0}',
   '{"category": "timing"}'),

-- Combined patterns
(9, 'panic_seller_pattern',
   'Panic Pattern Detected',
   'High turnover ({{turnover}}) + fast reaction ({{reactionTime}}) + volatility chasing ({{volatilityChasing}}) — this combination often signals panic trading. Take a breath.',
   '{"minTurnover": 2.5, "maxReactionTime": 2.0, "minVolatilityChasing": 0.5}',
   '{"category": "pattern"}'),

(10, 'steady_investor_pattern',
    'Steady Investor',
    'Low turnover ({{turnover}}), measured reactions ({{reactionTime}}), minimal chasing ({{volatilityChasing}}) — you''re showing the discipline of experienced investors.',
    '{"maxTurnover": 0.8, "minReactionTime": 3.0, "maxVolatilityChasing": 0.3}',
    '{"category": "pattern"}'),

-- Window-type specific
(11, 'spotlight_reactor',
    'Spotlight Chaser',
    'During an asset spotlight event, your turnover hit {{turnover}}. The hype cycle is real — most who buy at the peak regret it.',
    '{"minTurnover": 2.0, "windowType": "spotlight"}',
    '{"category": "event_response"}'),

(12, 'arc_aware',
    'Macro Awareness',
    'During a world arc shift, you kept turnover at {{turnover}} and chasing at {{volatilityChasing}}. Understanding macro trends without overreacting is a valuable skill.',
    '{"maxTurnover": 1.0, "maxVolatilityChasing": 0.3, "windowType": "arc"}',
    '{"category": "event_response"}'),

(13, 'policy_panic',
    'Policy Panic',
    'Policy announcement triggered heavy trading (turnover: {{turnover}}). Policy changes take months to impact markets — the initial reaction is often an overreaction.',
    '{"minTurnover": 2.0, "windowType": "policy"}',
    '{"category": "event_response"}'),

(14, 'diamond_hands',
    'Diamond Hands',
    'Zero trades during market volatility. Whether this is conviction or inattention, the result is the same — you avoided panic selling.',
    '{"maxTurnover": 0.0}',
    '{"category": "pattern"}'),

(15, 'fomo_detected',
    'FOMO Alert',
    'Volatility chasing ({{volatilityChasing}}) combined with increasing concentration ({{concentrationChange}}) — classic fear of missing out. The best opportunities are often in what nobody is talking about.',
    '{"minVolatilityChasing": 0.5, "minConcentrationChange": 0.10}',
    '{"category": "pattern"}');

-- ============================================================
-- 8. MISSIONS
-- ============================================================
INSERT INTO invest.missions (id, code, title, description, condition, reward_credits) VALUES
-- Diversification missions
(1, 'diversifier',
   'The Diversifier',
   'Hold positions in at least 3 different sectors.',
   '{"minSectorCount": 3}',
   500),

(2, 'well_rounded',
   'Well Rounded',
   'Hold positions in all 4 sectors simultaneously.',
   '{"minSectorCount": 4}',
   1500),

(3, 'collector',
   'Asset Collector',
   'Hold at least 8 different asset positions.',
   '{"minPositionCount": 8}',
   1000),

-- Stability missions
(4, 'steady_hand',
   'Steady Hand',
   'Achieve a stability factor of 1.3 or higher.',
   '{"minStabilityFactor": 1.3}',
   2000),

(5, 'rock_solid',
   'Rock Solid',
   'Achieve a stability factor of 1.7 or higher.',
   '{"minStabilityFactor": 1.7}',
   5000),

-- Trading behavior missions
(6, 'zen_trader',
   'Zen Trader',
   'Complete 3 behavior windows with average turnover below 0.5.',
   '{"minSnapshotCount": 3, "maxAvgTurnover": 0.5}',
   1500),

(7, 'active_participant',
   'Active Participant',
   'Complete at least 5 behavior windows (have at least 5 snapshots).',
   '{"minSnapshotCount": 5}',
   800),

(8, 'patient_holder',
   'Patient Holder',
   'Maintain a stability factor above 1.2 with average volatility chasing below 0.2.',
   '{"minStabilityFactor": 1.2, "maxAvgVolatilityChasing": 0.2}',
   2500),

-- Wealth tier missions
(9, 'first_50k',
   'Getting Started',
   'Reach the Developing wealth tier (50,000+ wealth points).',
   '{"minWealthPoints": 50000}',
   1000),

(10, 'steady_climber',
    'Steady Climber',
    'Reach the Steady wealth tier (100,000+ wealth points).',
    '{"minWealthPoints": 100000}',
    3000),

(11, 'advanced_investor',
    'Advanced Investor',
    'Reach the Advanced wealth tier (200,000+ wealth points).',
    '{"minWealthPoints": 200000}',
    5000),

(12, 'elite_status',
    'Elite Status',
    'Reach the Elite wealth tier (500,000+ wealth points).',
    '{"minWealthPoints": 500000}',
    10000),

-- Portfolio composition missions
(13, 'crypto_curious',
    'Crypto Curious',
    'Hold at least 3 different crypto assets.',
    '{"minCryptoPositions": 3}',
    500),

(14, 'real_estate_mogul',
    'Real Estate Mogul',
    'Hold at least 3 different real estate assets.',
    '{"minRealEstatePositions": 3}',
    500),

(15, 'commodity_king',
    'Commodity King',
    'Hold at least 3 different commodity assets.',
    '{"minCommodityPositions": 3}',
    500),

-- Risk-aware missions
(16, 'risk_aware',
    'Risk Aware',
    'Keep volatility chasing below 0.15 across 3 consecutive behavior windows.',
    '{"minSnapshotCount": 3, "maxAvgVolatilityChasing": 0.15}',
    2000),

(17, 'contrarian',
    'The Contrarian',
    'Maintain positions while others panic — stability factor above 1.4 with at least 5 snapshots.',
    '{"minStabilityFactor": 1.4, "minSnapshotCount": 5}',
    3000),

(18, 'market_survivor',
    'Market Survivor',
    'Complete 10 behavior windows without going below starting credits.',
    '{"minSnapshotCount": 10, "minWealthPoints": 100000}',
    5000);

-- ============================================================
-- 10. ARC → SPOTLIGHT TEMPLATE MAPPINGS
-- Each arc type maps to spotlight templates with matching sentiment.
-- weight: 0.0–1.0 (higher = more likely to be selected)
-- ============================================================
INSERT INTO invest.arc_spotlight_templates (arc_type_id, template_id, weight) VALUES
-- Arc 1: AI Revolution (bullish tech)
(1, 4,  1.0),   -- earnings_surprise (bullish) — AI chip demand → earnings beat
(1, 5,  0.8),   -- partnership_rumor (bullish) — AI partnership deals
(1, 9,  0.6),   -- influencer_pump (bullish) — influencers tout AI stocks
(1, 7,  0.4),   -- listing_hype (bullish) — AI companies IPO
(1, 1,  0.3),   -- viral_meme (bullish) — AI memes go viral

-- Arc 2: Green Energy Transition (bullish energy/clean)
(2, 5,  1.0),   -- partnership_rumor — green energy partnerships
(2, 4,  0.8),   -- earnings_surprise — green earnings beat
(2, 7,  0.6),   -- listing_hype — clean energy IPOs
(2, 11, 0.5),   -- dividend_boost — utility dividends up
(2, 9,  0.4),   -- influencer_pump — ESG influencers

-- Arc 3: Interest Rate Hike Cycle (bearish growth, bullish value)
(3, 12, 1.0),   -- insider_sell (bearish) — insiders sell before rate hike
(3, 8,  0.8),   -- regulatory_probe (bearish) — Fed scrutiny
(3, 11, 0.6),   -- dividend_boost (bullish) — dividend stocks attractive
(3, 3,  0.4),   -- whale_move (mixed) — portfolio rotation

-- Arc 4: Global Supply Chain Shock (bearish)
(4, 12, 1.0),   -- insider_sell — supply chain risk
(4, 8,  0.8),   -- regulatory_probe — trade investigations
(4, 6,  0.6),   -- hack_scare — logistics system vulnerabilities
(4, 3,  0.4),   -- whale_move — flight from affected stocks

-- Arc 5: Emerging Market Boom (bullish)
(5, 4,  1.0),   -- earnings_surprise — EM earnings growth
(5, 5,  0.8),   -- partnership_rumor — cross-border deals
(5, 7,  0.7),   -- listing_hype — EM listings
(5, 9,  0.5),   -- influencer_pump — EM bull narratives

-- Arc 6: Crypto Regulation Wave (bearish crypto)
(6, 8,  1.0),   -- regulatory_probe — regulatory crackdown
(6, 6,  0.8),   -- hack_scare — security concerns driving regulation
(6, 12, 0.7),   -- insider_sell — insiders exit before regulation
(6, 3,  0.4),   -- whale_move — whales repositioning

-- Arc 7: Housing Market Correction (bearish real estate)
(7, 12, 1.0),   -- insider_sell — developers selling
(7, 8,  0.8),   -- regulatory_probe — housing market scrutiny
(7, 3,  0.5),   -- whale_move — institutional repositioning
(7, 10, 0.3),   -- short_squeeze — short sellers on REITs

-- Arc 8: Deglobalization Trend (mixed)
(8, 5,  1.0),   -- partnership_rumor — domestic partnership deals
(8, 4,  0.7),   -- earnings_surprise — onshoring beneficiaries
(8, 8,  0.6),   -- regulatory_probe — trade policy investigations
(8, 12, 0.5);   -- insider_sell — global-exposed companies

-- ============================================================
-- 11. ARC → ASSET AFFINITY MAPPINGS
-- How strongly each asset relates to each arc narrative.
-- affinity: 0.0–1.0 (higher = more likely to get spotlight)
-- Only assets with affinity > 0 are listed.
-- ============================================================
INSERT INTO invest.arc_asset_affinities (arc_type_id, asset_id, affinity) VALUES
-- Arc 1: AI Revolution
(1, 10008, 1.00),  -- NVIDEAH — GPU/AI chip, direct beneficiary
(1, 10002, 0.90),  -- MICROHARD — Azure AI, cloud infra
(1, 10006, 0.90),  -- GOOGEL — DeepMind, AI search
(1, 10003, 0.70),  -- AMAYZON — AWS AI services
(1, 10007, 0.60),  -- METAH — AI in social/VR
(1, 10001, 0.50),  -- APPLZ — Apple Intelligence
(1, 10005, 0.50),  -- TESLAAH — self-driving AI
(1, 10004, 0.20),  -- NETFLICKS — AI recommendation (weak)
(1, 10009, 0.10),  -- SPOTIFYD — AI playlist (weak)
(1, 11002, 0.30),  -- ETHEREAL — AI + smart contracts
(1, 11010, 0.25),  -- GASGOD — compute demand
(1, 13007, 0.20),  -- COPPERHEAD — data center wiring

-- Arc 2: Green Energy Transition
(2, 10005, 1.00),  -- TESLAAH — EV, clean energy direct
(2, 13006, 0.90),  -- URANIUMZ — nuclear energy
(2, 13005, 0.80),  -- OILISH — energy transition pressure (inverse but high attention)
(2, 10001, 0.40),  -- APPLZ — renewable supply chain
(2, 10003, 0.30),  -- AMAYZON — logistics electrification
(2, 13007, 0.70),  -- COPPERHEAD — copper for EV/solar
(2, 12003, 0.30),  -- SKYHIGH — green buildings
(2, 12006, 0.25),  -- WAREHOUSE — EV charging infra

-- Arc 3: Interest Rate Hike Cycle
(3, 10005, 0.90),  -- TESLAAH — growth stock, rate sensitive
(3, 10007, 0.80),  -- METAH — growth stock
(3, 10010, 0.70),  -- UBEAR — high burn rate
(3, 11003, 0.80),  -- DOGGO — speculative crush
(3, 11004, 0.80),  -- MOONER — speculative crush
(3, 11007, 0.70),  -- FOMO — risk-off
(3, 12001, 0.60),  -- METACONDO — mortgage rates
(3, 12002, 0.60),  -- SUBURBIA — mortgage rates
(3, 13001, 0.50),  -- GOLDY — safe haven
(3, 13002, 0.40),  -- SILVERBACK — safe haven

-- Arc 4: Global Supply Chain Shock
(4, 10008, 0.90),  -- NVIDEAH — chip shortage
(4, 10001, 0.70),  -- APPLZ — hardware supply chain
(4, 10003, 0.60),  -- AMAYZON — logistics disruption
(4, 13005, 0.80),  -- OILISH — energy spike
(4, 13008, 0.70),  -- WHEATY — food supply
(4, 13007, 0.60),  -- COPPERHEAD — metals shortage
(4, 12006, 0.50),  -- WAREHOUSE — logistics demand

-- Arc 5: Emerging Market Boom
(5, 11001, 0.80),  -- BITZ — EM crypto adoption
(5, 11002, 0.70),  -- ETHEREAL — EM DeFi growth
(5, 10003, 0.60),  -- AMAYZON — EM expansion
(5, 10010, 0.50),  -- UBEAR — EM mobility
(5, 13007, 0.70),  -- COPPERHEAD — infrastructure build
(5, 12001, 0.40),  -- METACONDO — EM property
(5, 12003, 0.40),  -- SKYHIGH — EM commercial

-- Arc 6: Crypto Regulation Wave
(6, 11003, 1.00),  -- DOGGO — meme coin devastated
(6, 11004, 0.90),  -- MOONER — meme crush
(6, 11005, 0.90),  -- RUGGY — regulation target
(6, 11009, 0.80),  -- APECHAIN — meme regulatory risk
(6, 11007, 0.80),  -- FOMO — speculative target
(6, 11008, 0.70),  -- DEFIANT — DeFi compliance costs
(6, 11001, 0.50),  -- BITZ — regulatory scrutiny
(6, 11002, 0.50),  -- ETHEREAL — smart contract regulation
(6, 11006, 0.30),  -- STABLEISH — actually benefits (low affinity = less spotlight needed)

-- Arc 7: Housing Market Correction
(7, 12010, 1.00),  -- FLIPSTER — flipping destroyed
(7, 12001, 0.80),  -- METACONDO — residential hit
(7, 12002, 0.80),  -- SUBURBIA — residential hit
(7, 12009, 0.70),  -- RENTMAX — rental pressure
(7, 12008, 0.60),  -- COZYCRIB — affordable housing
(7, 12003, 0.50),  -- SKYHIGH — commercial follows
(7, 12005, 0.40),  -- MALLCORE — retail RE
(7, 12004, 0.30),  -- BEACHY — hospitality RE

-- Arc 8: Deglobalization Trend
(8, 10008, 0.70),  -- NVIDEAH — supply chain reshoring
(8, 10001, 0.60),  -- APPLZ — hardware onshoring
(8, 13005, 0.60),  -- OILISH — energy independence
(8, 13008, 0.50),  -- WHEATY — food security
(8, 12006, 0.60),  -- WAREHOUSE — domestic logistics
(8, 11001, 0.40),  -- BITZ — borderless narrative
(8, 13007, 0.40);  -- COPPERHEAD — domestic mining

-- ============================================================
-- Reset sequences to avoid ID conflicts
-- ============================================================
SELECT setval(pg_get_serial_sequence('invest.world_arc_instances', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.world_arc_instances));
SELECT setval(pg_get_serial_sequence('invest.asset_spotlight_templates', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.asset_spotlight_templates));
SELECT setval(pg_get_serial_sequence('invest.asset_spotlight_instances', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.asset_spotlight_instances));
SELECT setval(pg_get_serial_sequence('invest.policy_thread_templates', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.policy_thread_templates));
SELECT setval(pg_get_serial_sequence('invest.policy_thread_instances', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.policy_thread_instances));
SELECT setval(pg_get_serial_sequence('invest.policy_sector_impacts', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.policy_sector_impacts));
SELECT setval(pg_get_serial_sequence('invest.world_arc_sector_impacts', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.world_arc_sector_impacts));
SELECT setval(pg_get_serial_sequence('invest.arc_spotlight_templates', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.arc_spotlight_templates));
SELECT setval(pg_get_serial_sequence('invest.arc_asset_affinities', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.arc_asset_affinities));
SELECT setval(pg_get_serial_sequence('invest.reflection_templates', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.reflection_templates));
SELECT setval(pg_get_serial_sequence('invest.missions', 'id'), (SELECT COALESCE(MAX(id), 0) FROM invest.missions));

COMMIT;
